version: '3.8'

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./django/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./postgresql/.env


volumes:
  db: