version: '3.8'

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sqluser
      - POSTGRES_PASSWORD=sqlpass
      - POSTGRES_DB=dbname


volumes:
  db: