version: '3.8'

services:

  # NGINX Web server
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - web
    networks:
      - nginx-django-network

  # POSTGRES database
  postgresql:
    image: postgres:15
    container_name: postgresql
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./postgresql/.env
    depends_on:
     - vault
    networks:
      - postgres-django-network

  # Hashicorp vault
  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    env_file:
      ./vault/.env
    ports:
      - 8200:8200
    volumes:
      - ./vault/raft:/vault/raft
      - ./vault/config:/vault/config
    #  - ./vault/certs:/vault/certs
    cap_add:
      - IPC_LOCK
    entrypoint: /vault/config/init-vault.sh
    networks:
      - vault-django-network

  # Django app
  web:
    build: ./django
    container_name: web
    command: gunicorn --bind 0.0.0.0:8000 project_transcendence.wsgi:application
    volumes:
      - ./django/:/usr/src/app/
    env_file:
      - ./django/.env
    depends_on:
      - postgresql
      - vault
    networks:
      - nginx-django-network
      - postgres-django-network
      - vault-django-network

networks:
  nginx-django-network:
    driver: bridge
  postgres-django-network:
    driver: bridge
  vault-django-network:
    driver: bridge
  