version: '3.8'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - web
    networks:
      transcendence:
    #restart: always
    
  web:
    build: ./django
    container_name: web
    command: gunicorn --bind 0.0.0.0:8000 project_transcendence.wsgi:application
    volumes:
      - ./django/:/usr/src/app/
    env_file:
      - ./django/.env
    depends_on:
      - postgresql
    networks:
      transcendence:
    #restart: always

  postgresql:
    image: postgres:15
    container_name: postgresql
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./postgresql/.env
    networks:
      transcendence:
    #restart: always

  # vault:
  #   image: hashicorp/vault:1.17
  #   container_name: vault
  #   env_file:
  #     ./vault/.env
  #   ports:
  #     - 8200:8200
  #   volumes:
  #     - ./vault/:/vault/data
  #   cap_add:
  #     - IPC_LOCK
  #   command: serve

volumes:
  db:

networks:
  transcendence:
    driver: bridge