version: '3.8'

services:

  # NGINX Web server (and naxsi as WAF)
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - web
    networks:
      - nginx-django-network

  # POSTGRES database
  postgresql:
    image: postgres:15
    container_name: postgresql
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./postgresql/.env
    depends_on:
     - vault
    networks:
      - redis-postgres-django-network

 # Hashicorp vault
  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    env_file:
      ./vault/.env
    volumes:
      - ./vault/volume:/vault
      - ./vault/config:/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config="/config/vault-config.hcl"
    networks:
      - vault-django-network
    
  vault-init:
    image: hashicorp/vault:1.17
    container_name: vault-init
    volumes:
      - ./web/.env:/django/.env
      - ./vault/config:/config
    depends_on:
      - vault
    env_file:
      - ./vault/.env
    entrypoint:  /config/init.sh
    networks:
      - vault-django-network
    restart: on-failure
    
  # Redis
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - ./redis/data:/data
    networks:
      - redis-postgres-django-network

  # Django app
  web:
    build: ./web/django/
    container_name: web
    command: daphne -b 0.0.0.0 -p 8000 project_transcendence.asgi:application
    volumes:
      - ./web/django/:/usr/src/app/
    env_file:
      - ./web/.env
    depends_on:
      - redis
      - postgresql
      - vault
      - vault-init
    networks:
      - nginx-django-network
      - redis-postgres-django-network
      - vault-django-network
    restart: on-failure

networks:
  nginx-django-network:
    driver: bridge
  redis-postgres-django-network:
    driver: bridge
  vault-django-network:
    driver: bridge
  