# Generated by Django 5.1.3 on 2024-12-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0006_alter_lobby_lobby_id'),
        ('a_home', '0012_alter_lobby_lobby_id'),
    ]

    operations = [
    ]
