# Generated by Django 5.1.3 on 2024-12-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0018_alter_lobby_lobby_id'),
        ('a_home', '0019_alter_lobby_lobby_id'),
    ]

    operations = [
    ]
