# Generated by Django 5.1.3 on 2024-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0004_remove_profile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='a_users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_request',
            field=models.ManyToManyField(related_name='invite_request', to='a_users.profile'),
        ),
    ]
