# Generated by Django 5.1.3 on 2024-11-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0005_profile_friends_profile_pending_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='a_users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pending_request',
            field=models.ManyToManyField(blank=True, related_name='invite_request', to='a_users.profile'),
        ),
    ]
